# Generated by Django 3.2.6 on 2022-02-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('key', models.CharField(max_length=4, verbose_name='Сам ключ')),
            ],
            options={
                'verbose_name': 'Токен регистрации',
                'verbose_name_plural': 'Токены регистрации',
            },
        ),
    ]
