# Generated by Django 3.2.6 on 2022-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Полных лет'),
        ),
    ]
