# Generated by Django 3.2.6 on 2022-02-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_tokensignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('applicant', 'Соискатель'), ('employer', 'Работодатель')], default='applicant', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
