# Generated by Django 3.2.6 on 2022-02-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_company',
            field=models.CharField(default=1, max_length=200, verbose_name='Название компании'),
            preserve_default=False,
        ),
    ]
