# Generated by Django 3.2.6 on 2022-02-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_user_name_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название компании'),
        ),
    ]
