# Generated by Django 3.2.6 on 2022-02-07 18:21

import app_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0005_alter_user_name_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_account.models.get_image_name, verbose_name='Аватарка'),
        ),
    ]
