# Generated by Django 3.2.6 on 2022-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0008_alter_user_third_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Полных лет'),
        ),
    ]
