version: '3.3'
services:
  web_dev:
    build: config
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./config/:/home/config/
    ports:
      - 9000:9000
    env_file:
      - ./.env.dev
    depends_on:
      - db_dev

  daphne_dev:
    build:
      context: config
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - ./config/:/home/config/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_dev
      - redis_dev

  redis_dev:
    image: redis:alpine
    restart: always

  db_dev:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - 5432:5432

  nginx_dev:
    build: ./nginx_dev
    ports:
      - 80:80
    env_file:
      - ./.env.dev
    depends_on:
      - daphne_dev
volumes:
  postgres_data_dev: