version: '3.3'

services:
  web:
    build:
      context: ./config
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8111
    volumes:
      - static_volume:/home/app/config/staticfiles
      - media_volume:/home/app/config/media
    expose:
      - 8111
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env.prod.db

  daphne:
    build:
      context: config
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    restart: always

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/home/app/config/staticfiles
      - media_volume:/home/app/config/media
    ports:
      - 80:80
    depends_on:
      - web
      - daphne

volumes:
  postgres_data:
  static_volume:
  media_volume: