# Generated by Django 3.2.6 on 2022-02-12 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('removed', 'снят'), ('active', 'активен'), ('deleted', 'удалён'), ('inspection', 'на проверке'), ('revision', 'отправлен на доработку')], default='inspection', max_length=100, verbose_name='Статус')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('health_book', models.BooleanField(default=False, verbose_name='Санитарная книжка')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Наличие прививки')),
                ('no_profession', models.BooleanField(default=False, verbose_name='Нет профессии')),
                ('not_citizen', models.BooleanField(default=False, verbose_name='Не являюсь гражданином РФ')),
                ('total_service', models.PositiveIntegerField(default=0, verbose_name='Общий стаж')),
                ('driving_experience', models.PositiveIntegerField(default=0, verbose_name='Водительский стаж')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.city', verbose_name='Город')),
                ('driver_license', models.ManyToManyField(blank=True, related_name='questionnaire', to='app_profile.DriverLicense', verbose_name='Водительское удостоверение')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.profession', verbose_name='Профессия')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.region', verbose_name='Регион')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Анкета соискателя',
                'verbose_name_plural': 'Анкеты соискателей',
            },
        ),
    ]
