# Generated by Django 3.2.6 on 2022-05-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='WorkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Режим работы',
                'verbose_name_plural': 'Режимы работы',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('removed', 'снят'), ('active', 'активен'), ('deleted', 'удалён'), ('inspection', 'на проверке'), ('revision', 'отправлен на доработку')], default='inspection', max_length=100, verbose_name='Статус')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование вакансии')),
                ('money', models.PositiveIntegerField(default=0, help_text='В рублях', verbose_name='Размер заработной платы')),
                ('accommodation', models.BooleanField(default=False, verbose_name='Проживание')),
                ('food', models.BooleanField(default=False, verbose_name='Питание')),
                ('drive', models.BooleanField(default=False, verbose_name='Проезд')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.city', verbose_name='Город')),
                ('count_see', models.ManyToManyField(blank=True, related_name='vacancy_see', to=settings.AUTH_USER_MODEL, verbose_name='Просмотры')),
                ('count_sentence', models.ManyToManyField(blank=True, related_name='vacancy_sentence', to=settings.AUTH_USER_MODEL, verbose_name='Предложения')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.profession', verbose_name='Профессия')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.region', verbose_name='Регион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
                ('work_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_profile.workmode', verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('removed', 'снят'), ('active', 'активен'), ('deleted', 'удалён'), ('inspection', 'на проверке'), ('revision', 'отправлен на доработку')], default='inspection', max_length=100, verbose_name='Статус')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('health_book', models.BooleanField(default=False, verbose_name='Санитарная книжка')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Наличие прививки от коронавируса')),
                ('no_profession', models.BooleanField(default=False, verbose_name='Нет профессии')),
                ('not_citizen', models.BooleanField(default=False, verbose_name='Не являюсь гражданином РФ')),
                ('total_service', models.PositiveIntegerField(default=0, verbose_name='Общий стаж')),
                ('driving_experience', models.PositiveIntegerField(default=0, verbose_name='Водительский стаж')),
                ('self_propelled', models.BooleanField(default=False, help_text='просьба оставить комментарий в поле "Дополнительная информация"', verbose_name='Права на  управление самоходными машинами')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.city', verbose_name='Город')),
                ('count_see', models.ManyToManyField(blank=True, related_name='questionnaire_see', to=settings.AUTH_USER_MODEL, verbose_name='Просмотры')),
                ('count_sentence', models.ManyToManyField(blank=True, related_name='questionnaire_sentence', to=settings.AUTH_USER_MODEL, verbose_name='Предложения')),
                ('driver_license', models.ManyToManyField(blank=True, related_name='questionnaire', to='app_profile.DriverLicense', verbose_name='Водительское удостоверение')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.profession', verbose_name='Профессия')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.region', verbose_name='Регион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Анкета соискателя',
                'verbose_name_plural': 'Анкеты соискателей',
            },
        ),
    ]
