# Generated by Django 3.2.6 on 2022-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='self_propelled',
            field=models.BooleanField(default=False, help_text='просьба оставить комментарий в поле "Дополнительная информация"', verbose_name='Права на  управление самоходными машинами'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(null=True, verbose_name='Дополнительная информация'),
        ),
    ]
