# Generated by Django 3.2.6 on 2022-02-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_auto_20220217_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
