# Generated by Django 3.2.6 on 2022-02-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_alter_questionnaire_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.profession', verbose_name='Профессия'),
        ),
    ]
