# Generated by Django 3.2.6 on 2022-02-17 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_profile', '0004_alter_questionnaire_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='count_see',
            field=models.ManyToManyField(blank=True, related_name='questionnaire_see', to=settings.AUTH_USER_MODEL, verbose_name='Просмотры'),
        ),
    ]
