# Generated by Django 3.2.6 on 2022-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_auto_20220217_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='vaccinated',
            field=models.BooleanField(default=False, verbose_name='Наличие прививки от коронавируса'),
        ),
    ]
