# Generated by Django 3.2.6 on 2022-02-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0007_alter_questionnaire_vaccinated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='money',
            field=models.PositiveIntegerField(default=0, help_text='В рублях', verbose_name='Размер заработной платы'),
        ),
    ]
