# Generated by Django 3.2.6 on 2022-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.TextField(blank=True, null=True, verbose_name='Вставка в head')),
                ('url', models.SlugField(help_text='Не менять!', max_length=100, unique=True, verbose_name='Url страницы')),
                ('show_1', models.BooleanField(default=True, verbose_name='Показывать рекламу №1')),
                ('advertising_1', models.TextField(blank=True, null=True, verbose_name='Реклама № 1')),
                ('show_2', models.BooleanField(default=True, verbose_name='Показывать рекламу №2')),
                ('advertising_2', models.TextField(blank=True, null=True, verbose_name='Реклама № 2')),
                ('show_3', models.BooleanField(default=True, verbose_name='Показывать рекламу №3')),
                ('advertising_3', models.TextField(blank=True, null=True, verbose_name='Реклама № 3')),
                ('show_4', models.BooleanField(default=True, verbose_name='Показывать рекламу №4')),
                ('advertising_4', models.TextField(blank=True, null=True, verbose_name='Реклама № 4')),
                ('show_5', models.BooleanField(default=True, verbose_name='Показывать рекламу №5')),
                ('advertising_5', models.TextField(blank=True, null=True, verbose_name='Реклама № 5')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
