# Generated by Django 3.2.6 on 2022-05-11 11:02

import app_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(help_text='Минимальная рекомендуемая ширина __', upload_to=app_main.models.get_image_name, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фото для слайдера',
                'verbose_name_plural': 'Фотографии для слайдера',
            },
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='description_icon_1',
            field=models.TextField(blank=True, null=True, verbose_name='Описание плюса 1'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='description_icon_2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание плюса 2'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='description_main',
            field=models.TextField(blank=True, null=True, verbose_name='Описание главной страницы'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='title_icon_1',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок плюса 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='title_icon_2',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок плюса 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='title_main',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок главной страницы'),
            preserve_default=False,
        ),
    ]
