# Generated by Django 3.2.6 on 2022-05-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20220511_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='advertising_1',
            field=models.TextField(blank=True, null=True, verbose_name='Реклама № 1 (Главная)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='advertising_2',
            field=models.TextField(blank=True, null=True, verbose_name='Реклама № 2 (Списки)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='advertising_3',
            field=models.TextField(blank=True, null=True, verbose_name='Реклама № 3(Личный кабинет)'),
        ),
    ]
