# Generated by Django 3.2.6 on 2022-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20220514_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='advertising_6',
            field=models.TextField(blank=True, null=True, verbose_name='Реклама № 6'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='advertising_7',
            field=models.TextField(blank=True, null=True, verbose_name='Реклама № 7'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='advertising_8',
            field=models.TextField(blank=True, null=True, verbose_name='Реклама № 8'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='show_6',
            field=models.BooleanField(default=True, verbose_name='Показывать рекламу №6'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='show_7',
            field=models.BooleanField(default=True, verbose_name='Показывать рекламу №7'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='show_8',
            field=models.BooleanField(default=True, verbose_name='Показывать рекламу №8'),
        ),
    ]
